import json
from pathlib import Path

META_PATH = Path(__file__).parent.parent.parent / "data" / "meta.json"


def _load_meta() -> dict:
    with open(META_PATH) as f:
        return json.load(f)


def generate_pipeline_code(session_data: dict) -> str:
    dataset_id = session_data["dataset_id"]
    task_type  = session_data["task_type"]
    state      = session_data["pipeline_state"]

    meta       = _load_meta()
    target     = meta[dataset_id]["target"]
    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "# ─── ML Pipeline — Generated by ML Playground ───────────────────────────────",
        f"# Dataset : {meta[dataset_id]['name']}",
        f"# Task    : {task_type}",
        f"# Target  : {target}",
        "#",
        "# pip install scikit-learn xgboost lightgbm optuna pyarrow",
        "#",
        "# IMPORTANT: This pipeline is split-aware.",
        "# All transformers are fit on X_train ONLY.",
        "# They are then applied (transform only) to X_test.",
        "# This prevents data leakage and produces honest evaluation metrics.",
        "",
    ]

    # ── Imports ───────────────────────────────────────────────────────────────
    lines += [
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.model_selection import train_test_split, cross_val_score",
    ]

    if "missing_values" in state:
        t = state["missing_values"]["technique"]
        if t == "knn":
            lines.append("from sklearn.impute import KNNImputer")
        elif t == "mice":
            lines.append("from sklearn.experimental import enable_iterative_imputer  # noqa")
            lines.append("from sklearn.impute import IterativeImputer")

    if "encoding" in state:
        t = state["encoding"]["technique"]
        if t in ("label", "ordinal"):
            lines.append("from sklearn.preprocessing import LabelEncoder")

    if "feature_selection" in state:
        t = state["feature_selection"]["technique"]
        if t == "variance_threshold":
            lines.append("from sklearn.feature_selection import VarianceThreshold")
        elif t == "mutual_info":
            lines.append(
                "from sklearn.feature_selection import "
                "mutual_info_classif, SelectKBest"
            )

    if "scaling" in state:
        t = state["scaling"]["technique"]
        _scaler_imports = {
            "standard": "from sklearn.preprocessing import StandardScaler",
            "minmax":   "from sklearn.preprocessing import MinMaxScaler",
            "robust":   "from sklearn.preprocessing import RobustScaler",
            "maxabs":   "from sklearn.preprocessing import MaxAbsScaler",
            "quantile": "from sklearn.preprocessing import QuantileTransformer",
            "power":    "from sklearn.preprocessing import PowerTransformer",
        }
        if t in _scaler_imports:
            lines.append(_scaler_imports[t])

    model_name = state.get("model", {}).get("name", "random_forest")
    _model_imports = {
        "logistic_regression":  "from sklearn.linear_model import LogisticRegression",
        "random_forest":        "from sklearn.ensemble import RandomForestClassifier",
        "xgboost":              "from xgboost import XGBClassifier",
        "lightgbm":             "from lightgbm import LGBMClassifier",
        "decision_tree":        "from sklearn.tree import DecisionTreeClassifier",
        "knn":                  "from sklearn.neighbors import KNeighborsClassifier",
        "naive_bayes":          "from sklearn.naive_bayes import GaussianNB",
        "gradient_boosting":    "from sklearn.ensemble import GradientBoostingClassifier",
        "ridge":                "from sklearn.linear_model import Ridge",
        "lasso":                "from sklearn.linear_model import Lasso",
        "elasticnet":           "from sklearn.linear_model import ElasticNet",
        "svr":                  "from sklearn.svm import SVR",
        "random_forest_reg":    "from sklearn.ensemble import RandomForestRegressor",
        "xgboost_reg":          "from xgboost import XGBRegressor",
        "lightgbm_reg":         "from lightgbm import LGBMRegressor",
        "knn_reg":              "from sklearn.neighbors import KNeighborsRegressor",
    }
    if model_name in _model_imports:
        lines.append(_model_imports[model_name])

    lines += ["", ""]

    # ── Load data ─────────────────────────────────────────────────────────────
    lines += [
        "# ── 1. Load data ─────────────────────────────────────────────────────────────",
        'df = pd.read_csv("your_dataset.csv")  # replace with your file path',
        f'TARGET = "{target}"',
        "",
        "X_raw = df.drop(columns=[TARGET])",
        "y     = df[TARGET]",
        "",
    ]

    # ── Split FIRST ───────────────────────────────────────────────────────────
    stratify_arg = ", stratify=y" if task_type == "classification" else ""
    lines += [
        "# ── 2. Split FIRST — before any fitting ──────────────────────────────────────",
        "# This is the most important step for preventing data leakage.",
        "# No transformer should see X_test during fitting.",
        "X_train, X_test, y_train, y_test = train_test_split(",
        f"    X_raw, y, test_size=0.2, random_state=42{stratify_arg}",
        ")",
        "",
    ]

    step_num = 3

    # ── Missing values ────────────────────────────────────────────────────────
    if "missing_values" in state:
        t = state["missing_values"]["technique"]
        p = state["missing_values"]["params"]
        lines += [
            f"# ── {step_num}. Missing value handling ({t}) ───────────────────────────────────────",
            "numeric_cols = X_train.select_dtypes(include='number').columns.tolist()",
            "cat_cols     = X_train.select_dtypes(exclude='number').columns.tolist()",
        ]
        if t == "mean":
            lines += [
                "# Compute means from X_train only",
                "train_means = X_train[numeric_cols].mean()",
                "X_train[numeric_cols] = X_train[numeric_cols].fillna(train_means)",
                "X_test[numeric_cols]  = X_test[numeric_cols].fillna(train_means)",
                "for col in cat_cols:",
                "    mode = X_train[col].mode()[0]",
                "    X_train[col] = X_train[col].fillna(mode)",
                "    X_test[col]  = X_test[col].fillna(mode)",
            ]
        elif t == "median":
            lines += [
                "# Compute medians from X_train only",
                "train_medians = X_train[numeric_cols].median()",
                "X_train[numeric_cols] = X_train[numeric_cols].fillna(train_medians)",
                "X_test[numeric_cols]  = X_test[numeric_cols].fillna(train_medians)",
                "for col in cat_cols:",
                "    mode = X_train[col].mode()[0]",
                "    X_train[col] = X_train[col].fillna(mode)",
                "    X_test[col]  = X_test[col].fillna(mode)",
            ]
        elif t == "knn":
            n = p.get("n_neighbors", 5)
            lines += [
                f"imputer = KNNImputer(n_neighbors={n})",
                "# fit_transform on train, transform only on test",
                "X_train[numeric_cols] = imputer.fit_transform(X_train[numeric_cols])",
                "X_test[numeric_cols]  = imputer.transform(X_test[numeric_cols])",
                "for col in cat_cols:",
                "    mode = X_train[col].mode()[0]",
                "    X_train[col] = X_train[col].fillna(mode)",
                "    X_test[col]  = X_test[col].fillna(mode)",
            ]
        elif t == "mice":
            lines += [
                "imputer = IterativeImputer(max_iter=10, random_state=42)",
                "X_train[numeric_cols] = imputer.fit_transform(X_train[numeric_cols])",
                "X_test[numeric_cols]  = imputer.transform(X_test[numeric_cols])",
            ]
        elif t == "constant":
            fill = p.get("fill_value", 0)
            lines += [
                f"X_train = X_train.fillna({fill})",
                f"X_test  = X_test.fillna({fill})",
            ]
        elif t == "drop_rows":
            lines += [
                "# Drop missing rows from train only — never drop test rows",
                "X_train = X_train.dropna()",
                "y_train = y_train.loc[X_train.index]",
                "# Fill remaining test nulls with train medians",
                "train_medians = X_train[numeric_cols].median()",
                "X_test[numeric_cols] = X_test[numeric_cols].fillna(train_medians)",
            ]
        elif t == "drop_cols":
            threshold = p.get("threshold", 0.5)
            lines += [
                f"# Drop columns where train missing % > {int(threshold*100)}%",
                f"cols_to_drop = [c for c in X_train.columns if X_train[c].isnull().mean() > {threshold}]",
                "X_train = X_train.drop(columns=cols_to_drop)",
                "X_test  = X_test.drop(columns=[c for c in cols_to_drop if c in X_test.columns])",
            ]
        lines.append("")
        step_num += 1

    # ── Feature engineering ───────────────────────────────────────────────────
    if "feature_engineering" in state:
        t = state["feature_engineering"]["technique"]
        p = state["feature_engineering"]["params"]
        lines += [
            f"# ── {step_num}. Feature engineering ({t}) ──────────────────────────────────────────",
            "numeric_cols = X_train.select_dtypes(include='number').columns.tolist()",
        ]
        if t == "log_features":
            lines += [
                "for col in numeric_cols:",
                "    if (X_train[col] > 0).all() and (X_test[col] > 0).all():",
                "        X_train[f'log_{col}'] = np.log1p(X_train[col])",
                "        X_test[f'log_{col}']  = np.log1p(X_test[col])",
            ]
        elif t == "polynomial":
            lines += [
                "cols_to_use = numeric_cols[:5]",
                "for i, col1 in enumerate(cols_to_use):",
                "    for col2 in cols_to_use[i:]:",
                "        X_train[f'{col1}_x_{col2}'] = X_train[col1] * X_train[col2]",
                "        X_test[f'{col1}_x_{col2}']  = X_test[col1]  * X_test[col2]",
            ]
        elif t == "sqrt_features":
            lines += [
                "for col in numeric_cols:",
                "    if (X_train[col] >= 0).all():",
                "        X_train[f'sqrt_{col}'] = np.sqrt(X_train[col])",
                "        X_test[f'sqrt_{col}']  = np.sqrt(X_test[col])",
            ]
        elif t == "interaction":
            lines += [
                "cols_to_use = numeric_cols[:6]",
                "for i in range(len(cols_to_use)):",
                "    for j in range(i+1, len(cols_to_use)):",
                "        col1, col2 = cols_to_use[i], cols_to_use[j]",
                "        X_train[f'{col1}_times_{col2}'] = X_train[col1] * X_train[col2]",
                "        X_test[f'{col1}_times_{col2}']  = X_test[col1]  * X_test[col2]",
            ]
        elif t == "binning":
            n_bins = p.get("n_bins", 5)
            lines += [
                "# Compute bin edges from train, apply to both",
                f"for col in numeric_cols[:5]:",
                f"    _, bin_edges = pd.cut(X_train[col], bins={n_bins}, retbins=True, duplicates='drop')",
                f"    X_train[f'{{col}}_binned'] = pd.cut(X_train[col], bins=bin_edges, labels=False, include_lowest=True)",
                f"    X_test[f'{{col}}_binned']  = pd.cut(X_test[col],  bins=bin_edges, labels=False, include_lowest=True)",
            ]
        lines.append("")
        step_num += 1

    # ── Encoding ──────────────────────────────────────────────────────────────
    if "encoding" in state:
        t = state["encoding"]["technique"]
        lines += [
            f"# ── {step_num}. Encoding ({t}) ────────────────────────────────────────────────────",
            "cat_cols = X_train.select_dtypes(exclude='number').columns.tolist()",
        ]
        if t == "onehot":
            lines += [
                "# Fit get_dummies on train, align test columns to match",
                "X_train = pd.get_dummies(X_train, columns=cat_cols, drop_first=False)",
                "X_test  = pd.get_dummies(X_test,  columns=cat_cols, drop_first=False)",
                "# align ensures test has same columns as train, fills missing with 0",
                "X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)",
            ]
        elif t == "label":
            lines += [
                "for col in cat_cols:",
                "    le = LabelEncoder()",
                "    X_train[col] = le.fit_transform(X_train[col].astype(str))",
                "    # Map test using known classes; unseen categories → -1",
                "    le_map = {cls: idx for idx, cls in enumerate(le.classes_)}",
                "    X_test[col] = X_test[col].astype(str).map(le_map).fillna(-1).astype(int)",
            ]
        elif t == "frequency":
            lines += [
                "# Frequency map computed from train only",
                "for col in cat_cols:",
                "    freq_map = X_train[col].value_counts(normalize=True).to_dict()",
                "    X_train[col] = X_train[col].map(freq_map).fillna(0)",
                "    X_test[col]  = X_test[col].map(freq_map).fillna(0)",
            ]
        elif t == "target":
            lines += [
                "# Target encoding — means computed from train only (prevents leakage)",
                "global_mean = float(y_train.mean())",
                "for col in cat_cols:",
                "    means = y_train.groupby(X_train[col]).mean().to_dict()",
                "    X_train[col] = X_train[col].map(means).fillna(global_mean)",
                "    X_test[col]  = X_test[col].map(means).fillna(global_mean)",
            ]
        lines.append("")
        step_num += 1

    # ── Feature selection ─────────────────────────────────────────────────────
    if "feature_selection" in state:
        t = state["feature_selection"]["technique"]
        p = state["feature_selection"]["params"]
        lines += [
            f"# ── {step_num}. Feature selection ({t}) ─────────────────────────────────────────────",
            "numeric_cols = X_train.select_dtypes(include='number').columns.tolist()",
        ]
        if t == "variance_threshold":
            threshold = p.get("threshold", 0.01)
            lines += [
                f"sel = VarianceThreshold(threshold={threshold})",
                "sel.fit(X_train[numeric_cols])",
                "kept = [col for col, s in zip(numeric_cols, sel.get_support()) if s]",
                "X_train = X_train[kept]",
                "X_test  = X_test[[c for c in kept if c in X_test.columns]]",
            ]
        elif t == "correlation":
            threshold = p.get("threshold", 0.95)
            lines += [
                "# Compute correlations on train only",
                f"corr = X_train[numeric_cols].corr().abs()",
                "upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))",
                f"to_drop = [col for col in upper.columns if any(upper[col] > {threshold})]",
                "X_train = X_train.drop(columns=to_drop)",
                "X_test  = X_test.drop(columns=[c for c in to_drop if c in X_test.columns])",
            ]
        elif t == "mutual_info":
            k = p.get("k", 10)
            lines += [
                "# Fit selector on train only",
                f"sel = SelectKBest(mutual_info_classif, k={k})",
                "sel.fit(X_train[numeric_cols], y_train)",
                "kept = [col for col, s in zip(numeric_cols, sel.get_support()) if s]",
                "X_train = X_train[kept]",
                "X_test  = X_test[[c for c in kept if c in X_test.columns]]",
            ]
        lines.append("")
        step_num += 1

    # ── Scaling ───────────────────────────────────────────────────────────────
    if "scaling" in state:
        t = state["scaling"]["technique"]
        _scaler_constructors = {
            "standard": "StandardScaler()",
            "minmax":   "MinMaxScaler()",
            "robust":   "RobustScaler()",
            "maxabs":   "MaxAbsScaler()",
            "quantile": "QuantileTransformer(output_distribution='uniform', random_state=42)",
            "power":    "PowerTransformer(method='yeo-johnson')",
        }
        if t in _scaler_constructors:
            lines += [
                f"# ── {step_num}. Scaling ({t}) ──────────────────────────────────────────────────────",
                "numeric_cols = X_train.select_dtypes(include='number').columns.tolist()",
                f"scaler = {_scaler_constructors[t]}",
                "# fit on train, transform both — critical for no leakage",
                "X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])",
                "X_test[numeric_cols]  = scaler.transform(X_test[numeric_cols])",
                "",
            ]
            step_num += 1

    # ── Keep numeric only ─────────────────────────────────────────────────────
    lines += [
        f"# ── {step_num}. Keep numeric features only ───────────────────────────────────────────",
        "X_train = X_train.select_dtypes(include='number')",
        "X_test  = X_test.select_dtypes(include='number')",
        "# Align columns in case get_dummies produced different sets",
        "X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)",
        "",
    ]
    step_num += 1

    # ── Model ─────────────────────────────────────────────────────────────────
    _model_constructors = {
        "logistic_regression":  "LogisticRegression(max_iter=1000)",
        "random_forest":        "RandomForestClassifier(n_estimators=100, random_state=42)",
        "xgboost":              "XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0)",
        "lightgbm":             "LGBMClassifier(random_state=42, verbose=-1)",
        "decision_tree":        "DecisionTreeClassifier(random_state=42)",
        "knn":                  "KNeighborsClassifier()",
        "naive_bayes":          "GaussianNB()",
        "gradient_boosting":    "GradientBoostingClassifier(random_state=42)",
        "ridge":                "Ridge()",
        "lasso":                "Lasso()",
        "elasticnet":           "ElasticNet()",
        "svr":                  "SVR()",
    }
    constructor = _model_constructors.get(
        model_name,
        "RandomForestClassifier(n_estimators=100, random_state=42)",
    )

    lines += [
        f"# ── {step_num}. Train model ─────────────────────────────────────────────────────────",
        f"model = {constructor}",
        "model.fit(X_train, y_train)",
        "y_pred = model.predict(X_test)",
        "",
    ]
    step_num += 1

    # ── Evaluation ────────────────────────────────────────────────────────────
    if task_type == "classification":
        lines += [
            f"# ── {step_num}. Evaluation ───────────────────────────────────────────────────────────",
            "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report",
            "print(f'Accuracy    : {accuracy_score(y_test, y_pred):.4f}')",
            "print(f'F1 weighted : {f1_score(y_test, y_pred, average=\"weighted\", zero_division=0):.4f}')",
            "print(classification_report(y_test, y_pred, zero_division=0))",
            "",
            "# Cross-validation on training set only",
            f"from sklearn.model_selection import StratifiedKFold",
            "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)",
            "scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='f1_weighted')",
            "print(f'CV F1 mean  : {scores.mean():.4f} ± {scores.std():.4f}')",
        ]
    else:
        lines += [
            f"# ── {step_num}. Evaluation ───────────────────────────────────────────────────────────",
            "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score",
            "print(f'RMSE : {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}')",
            "print(f'MAE  : {mean_absolute_error(y_test, y_pred):.4f}')",
            "print(f'R²   : {r2_score(y_test, y_pred):.4f}')",
            "",
            "from sklearn.model_selection import KFold",
            "cv = KFold(n_splits=5, shuffle=True, random_state=42)",
            "scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='r2')",
            "print(f'CV R² mean : {scores.mean():.4f} ± {scores.std():.4f}')",
        ]

    lines += [
        "",
        "# Feature importance (if available)",
        "if hasattr(model, 'feature_importances_'):",
        "    fi = pd.Series(model.feature_importances_, index=X_train.columns)",
        "    print(fi.sort_values(ascending=False).head(10))",
    ]

    return "\n".join(lines)