import json
from pathlib import Path


def generate_pipeline_code(session_data: dict) -> str:
    dataset_id = session_data["dataset_id"]
    task_type = session_data["task_type"]
    state = session_data["pipeline_state"]

    meta_path = Path(__file__).parent.parent.parent / "data" / "meta.json"
    with open(meta_path) as f:
        meta = json.load(f)
    target = meta[dataset_id]["target"]

    lines = []

    # Header
    lines += [
        "# ─── ML Pipeline — Generated by ML Playground ───────────────────────────────",
        "# Dataset: " + meta[dataset_id]["name"],
        "# Task:    " + task_type,
        "# Target:  " + target,
        "",
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.model_selection import train_test_split, cross_val_score",
        "",
    ]

    # Conditional imports based on what steps were used
    if "missing_values" in state:
        t = state["missing_values"]["technique"]
        if t == "knn":
            lines.append("from sklearn.impute import KNNImputer")
        elif t == "mice":
            lines.append("from sklearn.experimental import enable_iterative_imputer  # noqa")
            lines.append("from sklearn.impute import IterativeImputer")

    if "encoding" in state:
        t = state["encoding"]["technique"]
        if t == "label":
            lines.append("from sklearn.preprocessing import LabelEncoder")
        elif t == "ordinal":
            lines.append("from sklearn.preprocessing import OrdinalEncoder")

    if "scaling" in state:
        t = state["scaling"]["technique"]
        scaler_imports = {
            "standard": "from sklearn.preprocessing import StandardScaler",
            "minmax":   "from sklearn.preprocessing import MinMaxScaler",
            "robust":   "from sklearn.preprocessing import RobustScaler",
            "maxabs":   "from sklearn.preprocessing import MaxAbsScaler",
            "quantile": "from sklearn.preprocessing import QuantileTransformer",
            "power":    "from sklearn.preprocessing import PowerTransformer",
        }
        if t in scaler_imports:
            lines.append(scaler_imports[t])

    if "feature_selection" in state:
        t = state["feature_selection"]["technique"]
        if t == "variance_threshold":
            lines.append("from sklearn.feature_selection import VarianceThreshold")
        elif t == "mutual_info":
            lines.append("from sklearn.feature_selection import mutual_info_classif, SelectKBest")

    # Model import
    model_name = state.get("model", {}).get("name", "random_forest")
    model_imports = {
        "logistic_regression":  "from sklearn.linear_model import LogisticRegression",
        "random_forest":        "from sklearn.ensemble import RandomForestClassifier",
        "xgboost":              "from xgboost import XGBClassifier",
        "lightgbm":             "from lightgbm import LGBMClassifier",
        "decision_tree":        "from sklearn.tree import DecisionTreeClassifier",
        "knn":                  "from sklearn.neighbors import KNeighborsClassifier",
        "naive_bayes":          "from sklearn.naive_bayes import GaussianNB",
        "gradient_boosting":    "from sklearn.ensemble import GradientBoostingClassifier",
        "ridge":                "from sklearn.linear_model import Ridge",
        "lasso":                "from sklearn.linear_model import Lasso",
        "elasticnet":           "from sklearn.linear_model import ElasticNet",
        "svr":                  "from sklearn.svm import SVR",
    }
    if model_name in model_imports:
        lines.append(model_imports[model_name])

    lines += ["", ""]

    # Load data
    lines += [
        "# ─── 1. Load data ────────────────────────────────────────────────────────────",
        f'df = pd.read_csv("your_dataset.csv")  # replace with your file',
        f'TARGET = "{target}"',
        "",
    ]

    # Missing values
    if "missing_values" in state:
        t = state["missing_values"]["technique"]
        p = state["missing_values"]["params"]
        lines += [
            "# ─── 2. Missing value handling ───────────────────────────────────────────────",
            "numeric_cols = df.select_dtypes(include='number').columns.tolist()",
            "cat_cols = df.select_dtypes(exclude='number').columns.tolist()",
        ]
        if t == "mean":
            lines += [
                "for col in numeric_cols: df[col].fillna(df[col].mean(), inplace=True)",
                "for col in cat_cols: df[col].fillna(df[col].mode()[0], inplace=True)",
            ]
        elif t == "median":
            lines += [
                "for col in numeric_cols: df[col].fillna(df[col].median(), inplace=True)",
                "for col in cat_cols: df[col].fillna(df[col].mode()[0], inplace=True)",
            ]
        elif t == "knn":
            n = p.get("n_neighbors", 5)
            lines += [
                f"imputer = KNNImputer(n_neighbors={n})",
                "df[numeric_cols] = imputer.fit_transform(df[numeric_cols])",
                "for col in cat_cols: df[col].fillna(df[col].mode()[0], inplace=True)",
            ]
        elif t == "mice":
            lines += [
                "imputer = IterativeImputer(max_iter=10, random_state=42)",
                "df[numeric_cols] = imputer.fit_transform(df[numeric_cols])",
                "for col in cat_cols: df[col].fillna(df[col].mode()[0], inplace=True)",
            ]
        elif t == "drop_rows":
            lines.append("df.dropna(inplace=True)")
        lines.append("")

    # Feature engineering
    if "feature_engineering" in state:
        t = state["feature_engineering"]["technique"]
        lines += [
            "# ─── 3. Feature engineering ──────────────────────────────────────────────────",
            "numeric_cols = [c for c in df.select_dtypes(include='number').columns if c != TARGET]",
        ]
        if t == "log_features":
            lines += [
                "for col in numeric_cols:",
                "    if (df[col] > 0).all():",
                "        df[f'log_{col}'] = np.log1p(df[col])",
            ]
        elif t == "polynomial":
            lines += [
                "from sklearn.preprocessing import PolynomialFeatures",
                "poly = PolynomialFeatures(degree=2, include_bias=False)",
                "poly_features = poly.fit_transform(df[numeric_cols[:5]])",
                "poly_df = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(numeric_cols[:5]))",
                "df = pd.concat([df, poly_df], axis=1)",
            ]
        elif t == "sqrt_features":
            lines += [
                "for col in numeric_cols:",
                "    if (df[col] >= 0).all():",
                "        df[f'sqrt_{col}'] = np.sqrt(df[col])",
            ]
        lines.append("")

    # Encoding
    if "encoding" in state:
        t = state["encoding"]["technique"]
        lines += [
            "# ─── 4. Encoding ─────────────────────────────────────────────────────────────",
            "cat_cols = [c for c in df.select_dtypes(exclude='number').columns if c != TARGET]",
        ]
        if t == "onehot":
            lines.append("df = pd.get_dummies(df, columns=cat_cols, drop_first=False)")
        elif t == "label":
            lines += [
                "for col in cat_cols:",
                "    le = LabelEncoder()",
                "    df[col] = le.fit_transform(df[col].astype(str))",
            ]
        elif t == "frequency":
            lines += [
                "for col in cat_cols:",
                "    freq_map = df[col].value_counts(normalize=True).to_dict()",
                "    df[col] = df[col].map(freq_map)",
            ]
        lines.append("")

    # Feature selection
    if "feature_selection" in state:
        t = state["feature_selection"]["technique"]
        p = state["feature_selection"]["params"]
        lines += [
            "# ─── 5. Feature selection ────────────────────────────────────────────────────",
        ]
        if t == "variance_threshold":
            threshold = p.get("threshold", 0.01)
            lines += [
                f"sel = VarianceThreshold(threshold={threshold})",
                "X_temp = df.drop(columns=[TARGET]).select_dtypes(include='number')",
                "sel.fit(X_temp)",
                "low_var = X_temp.columns[~sel.get_support()].tolist()",
                "df.drop(columns=low_var, inplace=True)",
            ]
        elif t == "correlation":
            threshold = p.get("threshold", 0.95)
            lines += [
                "X_temp = df.drop(columns=[TARGET]).select_dtypes(include='number')",
                f"corr_matrix = X_temp.corr().abs()",
                "upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))",
                f"to_drop = [col for col in upper.columns if any(upper[col] > {threshold})]",
                "df.drop(columns=to_drop, inplace=True)",
            ]
        lines.append("")

    # Scaling
    if "scaling" in state:
        t = state["scaling"]["technique"]
        scaler_constructors = {
            "standard": "StandardScaler()",
            "minmax":   "MinMaxScaler()",
            "robust":   "RobustScaler()",
            "maxabs":   "MaxAbsScaler()",
            "quantile": "QuantileTransformer(output_distribution='uniform', random_state=42)",
            "power":    "PowerTransformer(method='yeo-johnson')",
        }
        if t in scaler_constructors:
            lines += [
                "# ─── 6. Scaling ──────────────────────────────────────────────────────────────",
                "numeric_cols = [c for c in df.select_dtypes(include='number').columns if c != TARGET]",
                f"scaler = {scaler_constructors[t]}",
                "df[numeric_cols] = scaler.fit_transform(df[numeric_cols])",
                "",
            ]

    # Split + train
    model_constructors = {
        "logistic_regression":  "LogisticRegression(max_iter=1000)",
        "random_forest":        "RandomForestClassifier(n_estimators=100, random_state=42)",
        "xgboost":              "XGBClassifier(eval_metric='logloss', random_state=42, verbosity=0)",
        "lightgbm":             "LGBMClassifier(random_state=42, verbose=-1)",
        "decision_tree":        "DecisionTreeClassifier(random_state=42)",
        "knn":                  "KNeighborsClassifier()",
        "naive_bayes":          "GaussianNB()",
        "gradient_boosting":    "GradientBoostingClassifier(random_state=42)",
        "ridge":                "Ridge()",
        "lasso":                "Lasso()",
        "elasticnet":           "ElasticNet()",
        "svr":                  "SVR()",
    }
    constructor = model_constructors.get(model_name, "RandomForestClassifier(n_estimators=100, random_state=42)")

    lines += [
        "# ─── 7. Split & train ────────────────────────────────────────────────────────",
        "X = df.drop(columns=[TARGET]).select_dtypes(include='number')",
        "y = df[TARGET]",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
        "",
        f"model = {constructor}",
        "model.fit(X_train, y_train)",
        "",
    ]

    # Evaluation
    if task_type == "classification":
        lines += [
            "# ─── 8. Evaluation ───────────────────────────────────────────────────────────",
            "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score",
            "y_pred = model.predict(X_test)",
            "print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')",
            "print(f'F1 (weighted): {f1_score(y_test, y_pred, average=\"weighted\"):.4f}')",
            "scores = cross_val_score(model, X, y, cv=5, scoring='f1_weighted')",
            "print(f'CV F1 mean: {scores.mean():.4f} ± {scores.std():.4f}')",
        ]
    else:
        lines += [
            "# ─── 8. Evaluation ───────────────────────────────────────────────────────────",
            "from sklearn.metrics import mean_squared_error, r2_score",
            "y_pred = model.predict(X_test)",
            "print(f'RMSE: {mean_squared_error(y_test, y_pred, squared=False):.4f}')",
            "print(f'R²:   {r2_score(y_test, y_pred):.4f}')",
            "scores = cross_val_score(model, X, y, cv=5, scoring='r2')",
            "print(f'CV R² mean: {scores.mean():.4f} ± {scores.std():.4f}')",
        ]

    return "\n".join(lines)